config/routes.rb
Rails.application.routes.draw do
  resources :job_listings

  resources :job_apps

  root 'home#index'
  get 'home/index'

  devise_for :users
  resources :users

end

app/models/job_app.rb
class JobApp < ActiveRecord::Base
end

app/models/job_listing.rb
class JobListing < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/job_apps_controller.rb
class JobAppsController < ApplicationController
  before_action :set_job_app, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @job_apps = JobApp.all
    respond_with(@job_apps)
  end

  def show
    respond_with(@job_app)
  end

  def new
    @job_app = JobApp.new
    respond_with(@job_app)
  end

  def edit
  end

  def create
    @job_app = JobApp.new(job_app_params)
    @job_app.save
    respond_with(@job_app)
  end

  def update
    @job_app.update(job_app_params)
    respond_with(@job_app)
  end

  def destroy
    @job_app.destroy
    respond_with(@job_app)
  end

  private
    def set_job_app
      @job_app = JobApp.find(params[:id])
    end

    def job_app_params
      params.require(:job_app).permit(:link, :date_saved, :date_applied)
    end
end

app/controllers/job_listings_controller.rb
class JobListingsController < ApplicationController
  before_action :set_job_listing, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @job_listings = JobListing.all
    respond_with(@job_listings)
  end

  def show
    respond_with(@job_listing)
  end

  def new
    @job_listing = JobListing.new
    respond_with(@job_listing)
  end

  def edit
  end

  def create
    @job_listing = JobListing.new(job_listing_params)
    @job_listing.save
    respond_with(@job_listing)
  end

  def update
    @job_listing.update(job_listing_params)
    respond_with(@job_listing)
  end

  def destroy
    @job_listing.destroy
    respond_with(@job_listing)
  end

  private
    def set_job_listing
      @job_listing = JobListing.find(params[:id])
    end

    def job_listing_params
      params.require(:job_listing).permit(:url, :company, :title, :date_posted)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @users = User.all
    respond_with(@users)
  end

  def show
    respond_with(@user)
  end

  def new
    @user = User.new
    respond_with(@user)
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.save
    respond_with(@user)
  end

  def update
    @user.update(user_params)
    respond_with(@user)
  end

  def destroy
    @user.destroy
    respond_with(@user)
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params[:user]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_apps_helper.rb
module JobAppsHelper
end

app/helpers/job_listings_helper.rb
module JobListingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_navbar.html.haml
%nav#navigation.row
	%div.col-1-4
		%a{:href => root_path}
			%h1.site-title AppTrack
	%div.col-1-4

	%div.col-1-4
		%ul.menu-ul
			%li Dashboard
			%li About
			%li
				%a{:href => new_user_registration_path}
					%button.nav.sign-up-nav Sign Up
			%li
				%a{:href => new_user_session_path}
					%button.nav.login-nav Log In

app/views/home/index.html.haml
%section.job-listing
	%h2 Job Listings
	%br
	%button.add-job-listing Add Job 
	%br
	%table
		%th
			%td Job Title
			%td Company
			%td Date Posted
		%tr
			%td Software Engineer
			%td	Yogoshu Co.
			%td 6/15/15

app/views/job_apps/_form.html.erb
<%= form_for(@job_app) do |f| %>
  <% if @job_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_app.errors.count, "error") %> prohibited this job_app from being saved:</h2>

      <ul>
      <% @job_app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :date_saved %><br>
    <%= f.date_select :date_saved %>
  </div>
  <div class="field">
    <%= f.label :date_applied %><br>
    <%= f.date_select :date_applied %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_apps/edit.html.erb
<h1>Editing job_app</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_app %> |
<%= link_to 'Back', job_apps_path %>

app/views/job_apps/index.html.erb
<h1>Listing job_apps</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Date saved</th>
      <th>Date applied</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_apps.each do |job_app| %>
      <tr>
        <td><%= job_app.link %></td>
        <td><%= job_app.date_saved %></td>
        <td><%= job_app.date_applied %></td>
        <td><%= link_to 'Show', job_app %></td>
        <td><%= link_to 'Edit', edit_job_app_path(job_app) %></td>
        <td><%= link_to 'Destroy', job_app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job app', new_job_app_path %>

app/views/job_apps/new.html.erb
<h1>New job_app</h1>

<%= render 'form' %>

<%= link_to 'Back', job_apps_path %>

app/views/job_apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @job_app.link %>
</p>

<p>
  <strong>Date saved:</strong>
  <%= @job_app.date_saved %>
</p>

<p>
  <strong>Date applied:</strong>
  <%= @job_app.date_applied %>
</p>

<%= link_to 'Edit', edit_job_app_path(@job_app) %> |
<%= link_to 'Back', job_apps_path %>

app/views/job_listings/_form.html.erb
<%= form_for(@job_listing) do |f| %>
  <% if @job_listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_listing.errors.count, "error") %> prohibited this job_listing from being saved:</h2>

      <ul>
      <% @job_listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date_posted %><br>
    <%= f.date_select :date_posted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_listings/edit.html.erb
<h1>Editing job_listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_listing %> |
<%= link_to 'Back', job_listings_path %>

app/views/job_listings/index.html.erb
<h1>Listing job_listings</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Company</th>
      <th>Title</th>
      <th>Date posted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_listings.each do |job_listing| %>
      <tr>
        <td><%= job_listing.url %></td>
        <td><%= job_listing.company %></td>
        <td><%= job_listing.title %></td>
        <td><%= job_listing.date_posted %></td>
        <td><%= link_to 'Show', job_listing %></td>
        <td><%= link_to 'Edit', edit_job_listing_path(job_listing) %></td>
        <td><%= link_to 'Destroy', job_listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job listing', new_job_listing_path %>

app/views/job_listings/new.html.erb
<h1>New job_listing</h1>

<%= render 'form' %>

<%= link_to 'Back', job_listings_path %>

app/views/job_listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @job_listing.url %>
</p>

<p>
  <strong>Company:</strong>
  <%= @job_listing.company %>
</p>

<p>
  <strong>Title:</strong>
  <%= @job_listing.title %>
</p>

<p>
  <strong>Date posted:</strong>
  <%= @job_listing.date_posted %>
</p>

<%= link_to 'Edit', edit_job_listing_path(@job_listing) %> |
<%= link_to 'Back', job_listings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppTrack</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render :partial => 'home/navbar' %>
	<br><br><br><br>
	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

	<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>